// <auto-generated />
using System;
using AgentieTurism.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgentieTurism.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgentieTurism.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NrTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumarCI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PerioadaSejurDoritaSfarsit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PerioadaSejurDoritaStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieCI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatiuneDoritaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatiuneDoritaId");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("AgentieTurism.Data.Models.Sejur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataSfarsit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatiuneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatiuneId");

                    b.ToTable("Sejururi");
                });

            modelBuilder.Entity("AgentieTurism.Data.Models.Statiune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statiuni");
                });

            modelBuilder.Entity("AgentieTurism.Data.Models.Client", b =>
                {
                    b.HasOne("AgentieTurism.Data.Models.Statiune", "StatiuneDorita")
                        .WithMany("Clienti")
                        .HasForeignKey("StatiuneDoritaId");
                });

            modelBuilder.Entity("AgentieTurism.Data.Models.Sejur", b =>
                {
                    b.HasOne("AgentieTurism.Data.Models.Statiune", "Statiune")
                        .WithMany("Sejururi")
                        .HasForeignKey("StatiuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
